### PR TITLE
fix: parsing failed if json data contains unicode

### PR DESCRIPTION
**Pull request by nigma143**

### CODE REVIEW

**Comment by nigma143** [comment]
#52

**Comment by nigma143** [comment]
@christophwille алё!

**Comment by christophwille** [comment]
https://github.com/open-policy-agent/npm-opa-wasm/blob/39950c934a9b739f86aabc9215d7c05809aa0443/src/opa.js#L37

https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/TextEncoder "The TextEncoder() constructor returns a newly created [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) object that will generate a byte stream with UTF-8 encoding."

ok, UTF-8 is what is used by the default JS impl (text to utf8 bytes)

**Comment by christophwille** [comment]
https://github.com/christophwille/dotnet-opa-wasm/commit/8a25d4da423f11132808ba41bbe82c188b2d7691

I have made a few more changes (to make FastEvaluate work properly), but in general I went with your fix. Thanks! (and sorry it took so long to get around to this)

**Pull request closed without merging**
