### PR TITLE
Support builtin types other than string

### PR DESCRIPTION
**Pull request by willhausman**
The `capabilities.json` allows us to specify custom functions with a specific return type.  I would like to return a boolean, but `OpaPolicy.RegisterBuiltin(string, Func<string, bool> func)` is not a possible overload.  I do see that the `_registeredBuiltins` is a `Dictionary<string, object>` so it should be able to support what I'm after.

In this proposed solution, the `RegisterBuiltin` overloads are generics that wrap the callback parameter with another func to handle converting the object pointers to their correct types.

### CODE REVIEW

**Comment by christophwille** [comment]
https://github.com/christophwille/dotnet-opa-wasm/pull/22#issuecomment-958685402

We had that discussion before - why do we need a level of indirection at this layer?

**Comment by christophwille** [comment]
And one other thing comes to mind when deserializing this way (typed instead of string) - thread culture.

**Comment by willhausman** [comment]
> And one other thing comes to mind when deserializing this way (typed instead of string) - thread culture.

I don't follow what you mean by "deserializing this way."  The library currently does `JsonSerializer.Deserializer<string>(dumpedJsonValue)`.  The only thing I changed there was using generics to parameterize which type it gets deserialized as.

> [#22 (comment)](https://github.com/christophwille/dotnet-opa-wasm/pull/22#issuecomment-958685402)
> 
> We had that discussion before - why do we need a level of indirection at this layer?
> 
> Edit: https://github.com/christophwille/dotnet-opa-wasm/blob/master/src/Opa.Wasm.UnitTests/BuiltinTests.cs#L30 I mean doing it in the lambda (and then calling a typed method of yours)

Using a single lambda of known types (the arg addresses) in a closure, I can avoid using costly reflection to figure out which type the argument is to deserialize it correctly for a user. I do mean deserialize correctly, too. There are 2 problems with the way the library is currently written, and this solution solves both problems:

1. I cannot return anything to a rego from my custom function but strings.  This forces a rego to do an extra deserialization step that should have been the responsibility of the called function.
2. I can only pass strings to my custom function, and I do mean only strings.  If, in my rego I call `custom.func(3)`, the library will break because this will not properly deserialize.  Likewise for enumerables, or objects.
```csharp
json = DumpJson(addr); // value of json is "3" here, not "\"3\""
JsonSerializer.Deserialize<string>(json); // breaks
----
json = "[\"value\", \"object\"]";
JsonSerializer.Deserialize<string>(json); // breaks
```

If the goal is to have the library only return strings and let the caller do serialization concerns, then `DumpJson(addr)` needs to be returned directly - and this is immediately less convenient because even simple string parameters have to be deserialized by calling code. It would then also then be the user's responsibility to serialize a return type so the library only directly calls `LoadJson()` when returning a value.  Otherwise, you run the risk of different serializer settings being used between reads/writes.

**Comment by christophwille** [comment]
The (potential) issue re:culture - when you serialize a float say 3.14159 with US culture, you get exactly that. If you do it in a German culture, you get 3,14159. I haven't ever tried that with the new STJ serialization (but it happened with a different serializer way back in the day in SharpDevelop - we shipped settings that were serialized US, and the target system happened to be German, and obviously it didn't deserialize properly). We need to verify that.

**Comment by willhausman** [comment]
Ah, that's what you meant. I didn't think about that. I'll check it out later. I'm more curious to know about what the wasm will support. It might be in our interest to explicitly set SerializerSettings to force what opa expects.

I have another branch where I was starting to flesh out some abstractions to make Microsoft dependency injection simple. As part of that, there would be a serializer interface that users could configure to have the library use their settings instead of default. That's a much broader set of breaking changes, though, and probably worth a major version bump instead of a simple PR.

Thanks,

Will H.
________________________________

**Comment by willhausman** [comment]
Added a test that shows serialization working in `de-DE` culture.

This is noteworthy.  https://play.openpolicyagent.org/p/jbCZm4XTTd We really want to avoid putting the wrong serialization in place.  Suggests to me that maybe the library should concern itself with more serialization and just expose the ability to interact with raw json for the undaunted.

**Comment by christophwille** [comment]
> I have another branch where I was starting to flesh out some abstractions to make Microsoft dependency injection simple. As part of that, there would be a serializer interface that users could configure to have the library use their settings instead of default. That's a much broader set of breaking changes, though, and probably worth a major version bump instead of a simple PR.

can you please open an issue with your ideas (before doing a PR)?

**Comment by christophwille** [comment]
Thanks for your contribution!

**Pull request merged**
